


UPDATE [dbo].[INTERFAZ_PEDIDOS_MICROS_CFDI_PREPARA]
   SET [ESTATUS_PEDIDO] = 0
 WHERE [ESTATUS_PEDIDO] IS NULL


UPDATE [dbo].[INTERFAZ_PEDIDOS_MICROS_CFDI_PREPARA]
   SET [ELIMINA_ARTICULO] = 0
 WHERE [ELIMINA_ARTICULO] IS NULL

 
UPDATE [dbo].[INTERFAZ_PEDIDOS_MICROS_CFDI_PREPARA]
   SET [CAMBIO_CANTIDAD] = 0
 WHERE [CAMBIO_CANTIDAD] IS NULL

----SELECT *  FROM [dbo].[INTERFAZ_PEDIDOS_MICROS_CFDI_PREPARA]
--  SELECT FECHA, SUBSTRING(FECHA,1,4)+'-'+SUBSTRING(FECHA,5,2)+'-'+SUBSTRING(FECHA,7,2) FROM [dbo].[INTERFAZ_PEDIDOS_MICROS_CFDI_PREPARA]





--SELECT DATEDIFF(DAY,CAST((SUBSTRING(FECHA,1,4)+'-'+SUBSTRING(FECHA,5,2)+'-'+SUBSTRING(FECHA,7,2)) AS DATE),GETDATE()) FROM [dbo].[INTERFAZ_PEDIDOS_MICROS_CFDI_PREPARA] 
 

SELECT DISTINCT documento AS Documento,
				SUBSTRING(FECHA,1,4)+'-'+SUBSTRING(FECHA,5,2)+'-'+SUBSTRING(FECHA,7,2)  AS Fecha_Pedido,
				CONVERT(char(10), GetDate(),126)  AS Fecha_Actual,
				DATEDIFF(DAY,GETDATE(),CAST((SUBSTRING(FECHA,1,4)+'-'+SUBSTRING(FECHA,5,2)+'-'+SUBSTRING(FECHA,7,2)) AS DATE)) as Dias_Para_Entrega ,
		        UPPER(ALMACEN.[Cost Center]) AS DESTINO,
				COUNT(documento) AS No_Articulos
		   FROM [dbo].[INTERFAZ_PEDIDOS_MICROS_CFDI_PREPARA] AS PEDIDO
     INNER JOIN [dbo].[INTERFAZ_CFDI_CATALOGO_ALMACENES]  AS ALMACEN ON PEDIDO.destino = ALMACEN.Number
	      WHERE PEDIDO.ESTATUS_PEDIDO = 0
       GROUP BY documento ,
				SUBSTRING(FECHA,1,4)+'-'+SUBSTRING(FECHA,5,2)+'-'+SUBSTRING(FECHA,7,2),
				DATEDIFF(DAY,GETDATE(),CAST((SUBSTRING(FECHA,1,4)+'-'+SUBSTRING(FECHA,5,2)+'-'+SUBSTRING(FECHA,7,2)) AS DATE)) ,
		        UPPER(ALMACEN.[Cost Center])
				



		 SELECT SUBSTRING(FECHA,1,4)+'-'+SUBSTRING(FECHA,5,2)+'-'+SUBSTRING(FECHA,7,2)  AS FECHA_PEDIDO,
		        documento AS DOCUMENTO,
		        UPPER(ALMACEN.[Cost Center]) AS DESTINO,
				PEDIDO.descripcion_del_articulo AS ARTICULO,
				PEDIDO.UNIDAD_BASE AS CANTIDAD,
				PEDIDO.UNIDAD_EMBARQUE
		   FROM [dbo].[INTERFAZ_PEDIDOS_MICROS_CFDI_PREPARA] AS PEDIDO
     INNER JOIN [dbo].[INTERFAZ_CFDI_CATALOGO_ALMACENES]  AS ALMACEN ON PEDIDO.destino = ALMACEN.Number
	      WHERE PEDIDO.ESTATUS_PEDIDO = 0
       
	   SELECT * FROM [dbo].[INTERFAZ_PEDIDOS_MICROS_CFDI_PREPARA] AS PEDIDO